### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by jakepeyser** [jakepeyser/jakepeyser.com#9]
Start blog and embed into website

**Comment by jakepeyser** [comment]
After investigating several options (Ghost, Wordpress, etc) I've settled on the following process:
- Blog on Medium
- Render my posts inside container that pulls these using Medium API
    - As Medium posts can be retrieved as JSON, send for the list of my posts ~ i.e. `https://medium.com/@ev/latest?format=json`
    - Pull cover photo like so `https://cdn-images-1.medium.com/max/800/1*H7nd1WarLoVSCTO2kr9aJQ.gif` where 800=width
    - Users can select posts to render them in another view using `uniqueSlug` property
- Grab an individual post thru the API
    - Retrieve the post JSON like `https://medium.com/@ev/its-hard-to-be-surprised-anymore-but-geez-6e02dc90bea0?format=json`
    - Parse the JSON into renderable HTML
        - Focus on paragraphs, images, and videos
            - Video: Embed in iframe with `src=/media/a5ebd49cb2138a4ebc6d8ad532b2b918?postId=6e02dc90bea0`
        - Consider making this into a public npm module for publishing later
    - Create CSS to style the post appropriately

**Comment by jakepeyser** [comment]
Resources for reference:
- [Medium API Docs](https://github.com/Medium/medium-api-docs)
- [Medium Node.js SDK](https://github.com/Medium/medium-sdk-nodejs)
- [Medium OAuth Apps](https://medium.com/me/applications)
- [GitHub Issue thread about `GET /posts` API route](https://github.com/Medium/medium-api-docs/issues/30)
- [Example Medium post with video](https://medium.com/@ev/its-hard-to-be-surprised-anymore-but-geez-6e02dc90bea0#.egqmgco53)

**Comment by jakepeyser** [comment]
Change of plans...in an effort to decouple myself from a possibly unstable API (Medium), I am going to be self-hosting Ghost instead. Here is the process:

- Create a separate app to host Ghost (i.e. `jakepeyser-blog.herokuapp.com`)
- Store the DB files in a Heroku Postgres instance
- Create a CNAME for the `blog.jakepeyser.com` subdomain to hit this app
- Use a Ghost theme and custom restyle the header to look like the main app header

And wala! Self-hosted blog up and running on my own domain

**Comment by jakepeyser** [comment]
Blog is live -> http://blog.jakepeyser.com/

Look & feel is pretty close to the main site and I am happy with the result. Will reassess after the first few blogs

**Comment by anteloio** [comment]
Though this way we don't benefit from Medium community of readers ¯\\\_(ツ)_/¯

**Comment by jakepeyser** [comment]
That is a definite downside @fwuensche, but I chose to go with Ghost for the content/UI ownership and Markdown editor, among a number of other reasons. [You can read more on my decision here](http://blog.jakepeyser.com/making-the-blog/) if you'd like!
